### ISSUE TITLE
Request to include the ₿ (Bitcoin) currency symbol

### ISSUE THREAD

**Issue by joernroeder** [floriankarsten/space-grotesk#13]
i am really enjoying this type – thank you very much!
As it seems as Bitcoin ₿ got included into the currency symbols list of unicode and included in other fonts i would love to see it in space grotesk as well 🚀👩‍🚀.

https://twitter.com/ken_lunde/status/661351862155669506
https://www.unicode.org/L2/L2015/15254.htm#145-C7
https://twitter.com/brandonnuman/status/1135784460366929920
https://en.bitcoin.it/wiki/Bitcoin_symbol

**Comment by mightybart** [comment]
Added in 1.1.6
