### ISSUE TITLE
Geometric/Display alternates

### ISSUE THREAD

**Issue by gmosx** [floriankarsten/space-grotesk#15]
Thank you for this amazing font ❤️

I would like to suggest one stylistic alternate, namely rounder/wider, more geometric versions of some capital characters, e.g. 'O', 'C', 'G', etc. The characters would be closer to a circle. It would be useful when using the font for display purposes.

**Comment by mightybart** [comment]
Hello, first of all, thank you! I considered something similar before, but it was just way too outlandish. I decided to keep it closer to the source typeface (Space Mono), so this change is unlikely to happen in the future. But anyone interested in this, please, fork and customise! 🙃

**Comment by gmosx** [comment]
I am wondering if you could give me some pointers about what kind of tools (open-source?) I could use to make this customization?

**Comment by mightybart** [comment]
The Space Grotesk source file is a Glyphs App file (https://glyphsapp.com), unfortunately not an open-source software. But you could try open and edit the OTF files in FontForge (https://fontforge.org).
