### ISSUE TITLE
Add Space Grotesk to Google Fonts

### ISSUE THREAD

**Issue by gmosx** [floriankarsten/space-grotesk#16]
Adding the font to Google Fonts would help *a lot* with distribution. For example we could easily use this with Figma. I understand this might need some work, but it would be definitely worth it.

**Comment by mightybart** [comment]
Working on it 💪

**Comment by MizR** [comment]
+1  👍

**Comment by smashmiek** [comment]
+1 and a big thanks!

**Comment by davelab6** [comment]
Finally it is done :)

**Comment by mightybart** [comment]
🍾 🥂 Yessss! Thank you ❤️

**Comment by varunmashru** [comment]
I'm still unable to access the font on Figma directly via Google Fonts. Installing it on my machine seems to be the only way to get it to work.
