### ISSUE TITLE
U+220F N-ARY PRODUCT and U+2211 N-ARY SUMMATION are too short

### ISSUE THREAD

**Issue by dscorbett** [floriankarsten/space-grotesk#19]
U+220F N-ARY PRODUCT and U+2211 N-ARY SUMMATION should descend below the baseline, as is usual for <var>n</var>-ary operators. The current glyphs would be appropriate for U+03A0 GREEK CAPITAL LETTER PI and U+03A3 GREEK CAPITAL LETTER SIGMA instead. Here they are, with ⟨R⟩ for comparison:
![R∏∑](https://user-images.githubusercontent.com/1124347/80265571-006ab200-8666-11ea-8571-95dd616859a4.png)

**Comment by mightybart** [comment]
Fixed in [v2 branch](../tree/v2)
