### ISSUE TITLE
Awesome work - I'm sending you a Gitcash tip - trying it out atm, cheers

### ISSUE THREAD

**Issue by owenlord** [floriankarsten/space-grotesk#2]
@GitCash send .0095 bch to @floriankarsten

**Comment by GitCash** [comment]
Hey **floriankarsten**, user **owenlord** tipped you **9500 bits** in Bitcoin Cash ( ~ **$5.0065** ).

*[Click here to claim it!](https://gitcash.io/claim/floriankarsten)*

You can also add the "thumbs down" reaction to **owenlord**'s comment above to prevent future tips.
