### ISSUE TITLE
Incomplete stylistics sets

### ISSUE THREAD

**Issue by dscorbett** [floriankarsten/space-grotesk#33]
Some stylistic sets are incomplete.

'ss01' gives ⟨a⟩ a single-story glyph. All derivatives of ⟨a⟩ are affected too, except U+00AA FEMININE ORDINAL INDICATOR and U+0201 LATIN SMALL LETTER A WITH DOUBLE GRAVE. (It also skips ⟨æ⟩ but I assume that was intentional to avoid confusion with ⟨œ⟩.)
![aªȁ](https://user-images.githubusercontent.com/1124347/94367260-8ecae000-00ab-11eb-9416-619d9b415634.png)

'ss05' adds serifs to ⟨I⟩ and its derivatives, except U+0208 LATIN CAPITAL LETTER I WITH DOUBLE GRAVE, U+020A LATIN CAPITAL LETTER I WITH INVERTED BREVE, and U+1E2E LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE. (It also skips ⟨Ĳ⟩ but I assume that was intentional, since 'ss04' applies to that.)
![IȈȊḮ](https://user-images.githubusercontent.com/1124347/94367314-dea9a700-00ab-11eb-9bed-f90d3fcda6d2.png)

⟨B⟩ and its derivatives used to be sans-serif by default in previous versions, but now they have serifs by default, unless 'ss04' is enabled. The exceptions are U+0E3F THAI CURRENCY SYMBOL BAHT and U+20BF BITCOIN SIGN, which have no glyphs with serifs. Is that intentional?
![B฿₿](https://user-images.githubusercontent.com/1124347/94367405-845d1600-00ac-11eb-8269-f72cc3f5863f.png)

**Comment by mightybart** [comment]
👍 this needs to be fixed before release, definitely.

**Comment by dscorbett** [comment]
⟨B⟩ loses its serifs with 'ss04' but ⟨฿⟩ and ⟨₿⟩ now lose their serifs with 'ss03'. 'ss03' is for letters based on ⟨y⟩.

**Comment by mightybart** [comment]
🤦 thank you!
