### ISSUE TITLE
Problem with the letter «e» at a certain font-size

### ISSUE THREAD

**Issue by saschaeggi** [floriankarsten/space-grotesk#43]
I'm using Space Grotesk on my personal site and I love it: https://sascha.is/

If the font reaches 130px it somehow messes up the letter «e».
See screenshot:
<img width="598" alt="font_issue_130px" src="https://user-images.githubusercontent.com/5558166/136250864-888b9461-578b-4efb-ab69-d5d36036bb67.png">

Happens in Chrome & Brave. FF & Safari don't seem to have this issue.

Thanks a lot,
Sascha

**Comment by iskrisis** [comment]
hi Sascha, ive tried to replicate the issue with no luck. Are you certain this is issue with the typeface and not some recalculation issue for the effects you have on the website? There seems to be a lot going on that might mess things up.

I think we will need to have some way to isolate the issue to have any chance fixing it.

Cheers

**Comment by saschaeggi** [comment]
So I've done a quick Codepen to isolate & demonstrate the issue:
https://codepen.io/saschaeggi/pen/powMGZa

<img width="1068" alt="Screenshot 2021-10-07 at 14 42 52" src="https://user-images.githubusercontent.com/5558166/136386427-6a49d37d-a3f1-4731-a404-8cf358b7f6f2.png">

Doesn't happen at 129px or 131px. But does happen on 130px. It's very strange.
Can reproduce this with:
- Chrome, Version 94.0.4606.71 (Official Build) (x86_64)
- Brave, Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)

**Comment by iskrisis** [comment]
Thank you for making the codepen. I've tested it on these configurations:

OS:
macOS Monterey, macOS Big Sur, macOS Catalina, macOS Mojave, macOS High Sierra
Windows 10, Windows 8.1, Windows 8, Windows 7

With browsers:
Chrome 94, Chrome 93, Microsoft Edge 94 beta, Microsoft Edge 94, Safari (versions tied to OS), Firefox 93 beta, Firefox 92

None of the browsers showed the issue. 🤔 I wonder how this could happen. Can't it be some specific extension that you use in both browsers? Have you tried clean install or running chrome in safe mode?

**Comment by saschaeggi** [comment]
Updating Chrome to Version 94.0.4606.81 seems to fix the problem. So seemed to be a rendering issue in the Blink engine.

Sorry for the circumstances.
