### ISSUE TITLE
No distinction between lowercase L `l` and uppercase i `I`

### ISSUE THREAD

**Issue by victormihalache** [floriankarsten/space-grotesk#47]
There is not even a slight difference in the height of the letters, this can make it hard to read/funny to see in languages such as Italian where the world "il" ("the") is often at the beginning of a sentence, thus making it look like two vertical bars.

<img width="370" alt="Screenshot 2023-01-08 at 12 05 30 AM" src="https://user-images.githubusercontent.com/82441538/211173454-c154fcd0-f60f-4eb5-891a-df91b9f0b198.png">

Although most people will be able to read it, it is preferable to have a terminal for the lowercase l `l` at least otherwise it does look funny and a bit unprofessional.

To fix this I would propose adding two more stylistic sets: one where the uppercase I `I` gets serifs (some people just like that), and one where lowercase l `l` get a small terminal at the bottom (look at IBM Plex Sans).

**Comment by mightybart** [comment]
I'm sorry, most likely this won't be included in any future version.
