### ISSUE TITLE
What happened to the old alternate `g`?

### ISSUE THREAD

**Issue by brandonhaslegs** [floriankarsten/space-grotesk#48]
I know there was always the angular lowercase `g`, and the double-story alternate `g` but I also remember a more traditional (not 90º angle) `g`. How can I find it?

**Comment by iskrisis** [comment]
Please check the whole typeface [https://floriankarsten.github.io/space-grotesk/#opentype-features]().  It's probably in some stylistic set.

**Comment by brandonhaslegs** [comment]
I checked the whole typeface. Like I wrote, there is the standard angular `g` and an alternate `g`. Just wondering what happened to the other one. Here it is in a design I did a few years ago. 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/4406983/211558410-797b57f8-c8f1-44ef-8304-ad5eff7ad3ad.png">

It must be from an old version. Hopefully I can get it.

**Comment by iskrisis** [comment]
This is Space Grotesk v1. With v2 the effort was to put it more in line with Space Mono. You can get v1 from releases https://github.com/floriankarsten/space-grotesk/releases

**Comment by brandonhaslegs** [comment]
Fantastic thanks a lot!
