### ISSUE TITLE
Number 8 adjustment

### ISSUE THREAD

**Issue by domija** [floriankarsten/space-grotesk#5]
Really like the typeface except for the number 8, which has for my taste too big upper part, making the 8 look odd and unbalanced especially at smaller sizes. Would love to see the upper part a bit narrower.

**Comment by iskrisis** [comment]
Hi @domija, if just number 8 is a problem you can totaly fork the project and change this detail. Number 8 is one of the characters that are pretty much in line with design of Space Mono which was the typeface this typeface is based on.
